# Generated by Django 3.1.1 on 2020-11-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
