# Generated by Django 3.1.1 on 2020-11-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudStrife', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
