# Generated by Django 3.1.1 on 2020-11-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudStrife', '0002_auto_20201117_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(default='../images/defaul-avatar.png', max_length=30),
        ),
    ]
