# Generated by Django 3.1.1 on 2020-11-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudStrife', '0003_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(default='../../media/defaul-avatar.png', max_length=30),
        ),
    ]
