# Generated by Django 3.1.1 on 2020-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudStrife', '0004_auto_20201118_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
