# Generated by Django 3.1.1 on 2020-11-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudStrife', '0006_fotoperfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotoPerfil',
        ),
    ]
