# Generated by Django 3.1.1 on 2020-11-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudStrife', '0007_delete_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(default='../../media/defaul-avatar.png', max_length=200),
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('foto', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudStrife.usuario')),
            ],
        ),
    ]
