# Generated by Django 3.1.1 on 2020-11-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudStrife', '0008_auto_20201123_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('fecha', models.DateField()),
                ('usuario_creador', models.CharField(max_length=30)),
                ('foto_comentada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudStrife.foto')),
            ],
        ),
    ]
