# Generated by Django 3.1.1 on 2020-11-27 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudStrife', '0009_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguidore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidor', to='cloudStrife.usuario')),
                ('usuario_seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_seguido', to='cloudStrife.usuario')),
            ],
        ),
    ]
